runtime: php82
env: standard
instance_class: F1
handlers:
  - url: /assets/(.*)
    static_files: assets/\1
    upload: assets/.*
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: '301'
  - url: .*
    script: auto
automatic_scaling:
  max_instances: 1
  min_instances: 1
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: carihadiah-php@appspot.gserviceaccount.com